OskManager/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OskManager.Data;
using OskManager.Models;
using OskManager.BLL;
using OskManager.Models.CarsViewModels;
using Microsoft.AspNetCore.Authorization;

namespace OskManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICarsService _carsService;

        public CarsController(ApplicationDbContext context)
        {
            _context = context;
            _carsService = new CarsService(_context);
        }

        public async Task<IActionResult> Index()
        {
            return View(await _carsService.GetAllAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            var car = await _carsService.GetByIdAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Brand,Model,Year,RegistrationNumber")] AddEditCarViewModel car)
        {
            if (ModelState.IsValid)
            {
                Car newCar = new Car()
                {
                    Brand = car.Brand,
                    Model = car.Model,
                    Year = car.Year,
                    RegistrationNumber = car.RegistrationNumber,
                };

                await _carsService.CreateAsync(newCar);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var car = await _carsService.GetByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            else
            {
                AddEditCarViewModel toEdit = new AddEditCarViewModel()
                {
                    Brand = car.Brand,
                    Model = car.Model,
                    Year = car.Year,
                    RegistrationNumber = car.RegistrationNumber,
                };

                return View(toEdit);

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,Brand,Model,Year,RegistrationNumber")] AddEditCarViewModel toEdit)
        {
            if (ModelState.IsValid)
            {
                Car modifiedCar = new Car()
                {
                    Brand = toEdit.Brand,
                    Model = toEdit.Model,
                    Year = toEdit.Year,
                    RegistrationNumber = toEdit.RegistrationNumber,
                };

                await _carsService.UpdateAsync(id, modifiedCar);
                return RedirectToAction(nameof(Index));
            }
            return View(toEdit);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var car = await _carsService.GetByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _carsService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OskManager/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OskManager</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/navbar.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-default" id="RedMenu">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                @if (User.IsInRole("Admin"))
                {
                    <div class="navbar-collapse collapse" id="RedMenu">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fab fa-digital-ocean fa-lg"></i> Osk Manager</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kursanci<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Account" asp-action="RegisterStudent">Zarejestruj</a></li>
                                    <li><a asp-area="" asp-controller="Users" asp-action="Students">Lista kursantów</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instruktorzy<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Account" asp-action="RegisterInstructor">Zarejestruj</a></li>
                                    <li><a asp-area="" asp-controller="Users" asp-action="Instructors">Lista instruktorów</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zarządzanie kursami<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Courses" asp-action="Create">Dodaj kurs</a></li>
                                    <li><a asp-area="" asp-controller="Courses" asp-action="Index">Wyświetl kursy</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zarządzanie pojazdami<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Cars" asp-action="Create">Dodaj pojazd</a></li>
                                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Lista pojazdów</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Finanse<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Finances" asp-action="Payments">Wpłaty</a></li>
                                    <li><a asp-area="" asp-controller="Finances" asp-action="Debts">Należności</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zajęcia<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Admin" asp-action="Events">Zbliżające się</a></li>
                                    <li><a asp-area="" asp-controller="Admin" asp-action="PastEvents">Zakończone</a></li>
                                    <li><a asp-area="" asp-controller="Admin" asp-action="Calendar">Kalendarz</a></li>
                                </ul>
                            </li>
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                    }

                @if (User.IsInRole("Instructor"))
                {
                    <div class="navbar-collapse collapse" id="RedMenu">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fab fa-digital-ocean fa-lg"></i> Osk Manager</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Twoje zajęcia<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Instructor" asp-action="Events">Zbliżające się zajęcia</a></li>
                                    <li><a asp-area="" asp-controller="Instructor" asp-action="PastEvents">Zakończone</a></li>
                                </ul>
                            </li>
                            <li><a asp-area="" asp-controller="Instructor" asp-action="Calendar">Kalendarz</a></li>

                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                }

                @if (User.IsInRole("Student"))
                {
                    <div class="navbar-collapse collapse" id="RedMenu">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fab fa-digital-ocean fa-lg"></i> Osk Manager</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Twoje zajęcia<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Student" asp-action="Events">Zbliżające się zajęcia</a></li>
                                    <li><a asp-area="" asp-controller="Student" asp-action="PastEvents">Zakończone</a></li>
                                    <li><a asp-area="" asp-controller="DrivingLessons" asp-action="Index" asp-route-id="@UserManager.GetUserId(User)">Umów jazdy</a></li>
                                </ul>
                            </li>
                            <li><a asp-area="" asp-controller="Finances" asp-action="UserFinances" asp-route-id="@UserManager.GetUserId(User)">Wpłaty/Należności</a></li>

                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                }
            </div>
        </nav>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - OskManager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>